---
# playbook.yml
- name: 'Provision Image'
  hosts: default
  become: true
  vars:
# Swap Variables
    swap_file_path: /swapfile
    swap_file_size_mb: '2048'
    swap_swappiness: '60'
    swap_file_state: present
    swap_file_create_command: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}"
    swap_test_mode: false
# Postfix Variables
  # These settings are required in postfix.
    postfix_myhostname: "{{ ansible_fqdn }}"
    postfix_mydomain: "{{ ansible_domain | default('localdomain', true) }}"
    postfix_myorigin: "{{ ansible_domain | default('localdomain', true) }}"
  # To "listen" on public interfaces, set inet_interfaces to something like
  # "all" or the name of the interface, such as "eth0".
    postfix_inet_interfaces: "all"
  # Enable IPv4, and IPv6 if supported - if IPV4 only set to ipv4
    postfix_inet_protocols: all
  # Set a banner
    postfix_banner: "$myhostname ESMTP $mail_name (Ubuntu)"
  # The distination tells Postfix what mails to accept mail for.
    postfix_mydestination: modem7.com, $myhostname, localhost.$mydomain, localhost
  # To accept email from other machines, set the mynetworks to something like
  # "- 192.168.0.0/24".
    postfix_mynetworks:
      - 127.0.0.0/8
  # These settings change the role of the postfix server to a relay host.
  # postfix_relay_domains: "$mydestination"
  # If you want to forward emails to another central relay server, set relayhost.
  # use brackets to sent to the A-record of the relayhost.
    postfix_relayhost: "[smtp-relay.sendinblue.com]:587"
  # Set the restrictions for receiving mails.
    postfix_smtpd_recipient_restrictions:
      - permit_mynetworks
      - permit_sasl_authenticated
      - reject_unauth_destination
      - reject_invalid_hostname
      - reject_non_fqdn_hostname
      - reject_non_fqdn_sender
      - reject_non_fqdn_recipient
      - reject_unknown_sender_domain
      - reject_unknown_recipient_domain
      - reject_rbl_client sbl.spamhaus.org
      - reject_rbl_client cbl.abuseat.org
      - reject_rbl_client dul.dnsbl.sorbs.net
      - permit
    postfix_smtpd_sender_restrictions:
      - reject_unknown_sender_domain
  # The default SMTP TLS security level for the Postfix SMTP client
    postfix_smtp_tls_security_level: none
  # Whether or not to use the local biff service.
    postfix_biff: no
  # With locally submitted mail, append the string ".$mydomain" to addresses that have no ".domain" information
    postfix_append_dot_mydomain: no
  # Enable SASL authentication in the Postfix SMTP server.
    postfix_smtpd_sasl_auth_enable: yes
  # Postfix SMTP server SASL security options; as of Postfix 2.3 the list of available features depends on the SASL server implementation that is selected with smtpd_sasl_type.
    postfix_smtpd_sasl_security_options: noanonymous
  # The default SMTP TLS security level for the Postfix SMTP client; when a non-empty value is specified, this overrides the obsolete parameters smtp_use_tls, smtp_enforce_tls, and smtp_tls_enforce_peername.
    postfix_smtpd_tls_security_level: may
  # The location of Postfix README files that describe how to build, configure or operate a specific Postfix subsystem or feature.
    postfix_readme_directory: no
  roles:
    - postfix
    - swap